name: My Chip Zigbee NCP
device: MGM260PD32VNA
base_project: src/zigbee_ncp
filename: "mgm260p"
sdk: "simplicity_sdk:2025.6.2"
toolchain: "12.2.1.20221205"

gbl:
  fw_type: zigbee_ncp
  baudrate: 115200
  fw_variant: sw_flow

c_defines:
  SL_IOSTREAM_EUSART_VCOM_BAUDRATE: 115200
  SL_IOSTREAM_EUSART_VCOM_FLOW_CONTROL_TYPE: SL_IOSTREAM_EUSART_UART_FLOW_CTRL_SOFT # per pinout

  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL: EUSART0 # can be 0, 1, 2 or 3
  SL_IOSTREAM_EUSART_VCOM_PERIPHERAL_NO: 0 # can be 0, 1, 2 or 3

  SL_IOSTREAM_EUSART_VCOM_TX_PORT: SL_GPIO_PORT_A # per pinout
  SL_IOSTREAM_EUSART_VCOM_TX_PIN: 5 # per pinout

  SL_IOSTREAM_EUSART_VCOM_RX_PORT: SL_GPIO_PORT_A # per pinout
  SL_IOSTREAM_EUSART_VCOM_RX_PIN: 6 # per pinout

  SL_IOSTREAM_EUSART_VCOM_CTS_PORT: 0 # per pinout (0=disabled)
  SL_IOSTREAM_EUSART_VCOM_CTS_PIN: 0 # per pinout (0=disabled)

  SL_IOSTREAM_EUSART_VCOM_RTS_PORT: 0 # per pinout (0=disabled)
  SL_IOSTREAM_EUSART_VCOM_RTS_PIN: 0 # per pinout (0=disabled)

  SL_CLOCK_MANAGER_HFXO_CTUNE: 140 # per measurement (140 is default)

  SL_RAIL_UTIL_RSSI_OFFSET: 0
